<?php

return [
    1 => [
        'id' => 1,
        'name' => 'Personalized Gold Name Necklace',
        'short_name' => 'Name necklace',
        'category' => "Women's Jewelry",
        'collection' => "Women's Fashion",
        'price' => 50000,
        'original_price' => 65000,
        'discount_percent' => 23,
        'stock' => 18,
        'rating' => 3.5,
        'reviews_count' => 12,
        'image' => 'images/product-necklace.png',
        'description' => 'Elegant personalized necklace crafted with premium materials. Perfect for gifting or treating yourself to something special.',
    ],
    2 => [
        'id' => 2,
        'name' => 'Layered Pendant Necklace Set',
        'short_name' => 'Layered pendant set',
        'category' => "Women's Jewelry",
        'collection' => "Deals",
        'price' => 42000,
        'original_price' => 54000,
        'discount_percent' => 22,
        'stock' => 11,
        'rating' => 4.1,
        'reviews_count' => 20,
        'image' => 'images/product-necklace.png',
        'description' => 'A ready-to-wear layered pendant set with a polished finish and adjustable chain lengths.',
    ],
    3 => [
        'id' => 3,
        'name' => 'Pearl Detail Bracelet',
        'short_name' => 'Pearl bracelet',
        'category' => "Accessories",
        'collection' => "Women's Fashion",
        'price' => 28500,
        'original_price' => 35000,
        'discount_percent' => 19,
        'stock' => 24,
        'rating' => 4.4,
        'reviews_count' => 31,
        'image' => 'images/product-listing-reference.png',
        'description' => 'A soft statement bracelet with pearl details for everyday outfits and occasion styling.',
    ],
    4 => [
        'id' => 4,
        'name' => 'Classic Leather Card Holder',
        'short_name' => 'Leather card holder',
        'category' => "Men's Fashion",
        'collection' => "Men's Fashion",
        'price' => 18000,
        'original_price' => 0,
        'discount_percent' => 0,
        'stock' => 35,
        'rating' => 4.0,
        'reviews_count' => 9,
        'image' => 'images/product-listing-reference.png',
        'description' => 'Slim card holder with clean stitching, durable finishing, and room for daily essentials.',
    ],
    5 => [
        'id' => 5,
        'name' => 'Hydrating Glow Skincare Set',
        'short_name' => 'Glow skincare set',
        'category' => 'Beauty & Skincare',
        'collection' => 'Beauty',
        'price' => 73500,
        'original_price' => 88000,
        'discount_percent' => 16,
        'stock' => 16,
        'rating' => 4.7,
        'reviews_count' => 45,
        'image' => 'images/product-listing-reference.png',
        'description' => 'A complete glow set for cleanser, serum, and moisture care in a simple routine.',
    ],
    6 => [
        'id' => 6,
        'name' => 'Soft Glam Makeup Essentials',
        'short_name' => 'Makeup essentials',
        'category' => 'Makeup & Cosmetics',
        'collection' => 'Beauty',
        'price' => 61000,
        'original_price' => 76000,
        'discount_percent' => 20,
        'stock' => 14,
        'rating' => 4.5,
        'reviews_count' => 38,
        'image' => 'images/product-necklace.png',
        'description' => 'A compact makeup edit for everyday soft glam looks with warm, wearable tones.',
    ],
];
